### ISSUE TITLE
Alarm Uploader not working

### ISSUE THREAD

**Issue by Chanete** [goruck/smart-zoneminder#6]
Hi goruck. Great project!!!, I was thinking of building something much easier than your project but, finally I decided to keep on your work.

I'm having a problem with zm-s3-uploader.js I've installed all depencies and when I run node zm-s3-uploader.js  I get this

`module.js:550
    throw err;
    ^

Error: Cannot find module '../build/Release/zmq.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/smart-zoneminder/zm-s3-upload/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)`

I've tried to find module.js or zmq.node files to figure out if it was a path error, but they are not (at list as single files you can find with 'find') in my filesystem.

Any clue of what can be happening.

Thx in advance
Chano

**Comment by Chanete** [comment]
Forget it!! I've been digging with zerorpc and finally I found that I was missing libzmq3-dev. 

I just `apt-get install libzmq3-dev` and re-install zerorpc `npm install zeroprc` and now it works!!

Thx!!
